# -n specifies a name for the stage.
# -p defines special types of dependencie
# -d defines dependencies on these files. Notice that the source code itself is marked as a dependency as well.
# -o specifies an output directory for this script, which writes two files in it.

stages:
  rasters: # prepare raster data 
    cmd: python src/prepare_rasters.py 
    deps:
    - src/prepare_rasters.py
    - data/raw/costa_rica/
    - data/interim/costa_rica/
    params:
    - prepare_rasters.country
    - prepare_rasters.data
    - prepare_rasters.lulc_tif
    outs:
    - data/interim/costa_rica/

  polys: # prepare polygons (high confidence)
    cmd: python src/prepare_polys.py 
    deps:
    - src/prepare_polys.py
    - src/prepare_rasters.py
    - data/raw/costa_rica/
    - data/interim/costa_rica/
    params:
    - xx
    outs:
    - data/interim/costa_rica/
  
  points: # prepare labeled and unlabeled points
    cmd: python src/prepare_points.py 
    deps:
    - src/prepare_points.py
    - src/prepare_polys.py
    - data/raw/costa_rica/
    - data/interim/costa_rica/
    params:
    - xx
    outs:
    - data/interim/costa_rica/

  extract: # extract labeled and unlabeled pts
    cmd: python src/extract.py data/interim/labeled_pts.shp
    deps:
    - data/data.xml
    - src/extract.py
    params:
    - prepare.seed
    - prepare.split
    outs:
    - data/prepared
  
  clean: # prepare data for modeling
    cmd: python src/extract.py 
    deps:
    - data/data.xml
    - src/extract.py
    params:
    - prepare.seed
    - prepare.split
    outs:
    - data/prepared

  tune: # performs gridsearch to identify hyperparameters 
    cmd: python src/extract.py 
    deps:
    - data/data.xml
    - src/extract.py
    params:
    - prepare.seed
    - prepare.split
    outs:
    - data/prepared
  
  train: # trains the label propagation algorithm